name: microphone_example
description: >2-
  Example app demonstrating how to use the microphone plugin.
publish_to: 'none'

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  microphone:
    # When depending on this package from a real application you should use:
    #   microphone: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  just_audio: ^0.5.4
  just_audio_web: ^0.1.0

dev_dependencies:
  pedantic: ^1.9.2
