name: microphone_platform_interface
description: >2-
  A common platform interface for the microphone plugin used by the different platform
  implementations.
version: 0.1.0+1
homepage: >2-
  https://github.com/creativecreatorormaybenot/microphone/tree/main/microphone_platform_interface

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.1.2
  pedantic: ^1.11.0
